# Generated by Django 4.2.2 on 2024-04-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='csv_file',
            field=models.FileField(default='', upload_to='csv_files/'),
        ),
    ]
