# Generated by Django 4.2.2 on 2024-04-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_project_csv_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='csv_file',
            field=models.FileField(blank=True, default='', null=True, upload_to='csv_files/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
