# Generated by Django 4.2.2 on 2024-04-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_project_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='csv_file',
        ),
        migrations.AddField(
            model_name='project',
            name='original_csv_file',
            field=models.FileField(blank=True, default='', null=True, upload_to='original_csv_files/'),
        ),
        migrations.AddField(
            model_name='project',
            name='processed_csv_file',
            field=models.FileField(blank=True, default='', null=True, upload_to='processed_csv_files/'),
        ),
    ]
