# Generated by Django 4.2.2 on 2024-04-06 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_project_csv_file_project_original_csv_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
    ]
