# Generated by Django 4.2.2 on 2024-04-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_visualization'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualization',
            name='feature_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
